---
- name: Generate private keys
  shell: openssl genrsa 4096 > {{ letsencrypt_keys_dir }}/{{ item.key }}.key
  args:
    creates: "{{ letsencrypt_keys_dir }}/{{ item.key }}.key"
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Ensure correct permissions on private keys
  file:
    path: "{{ letsencrypt_keys_dir }}/{{ item.key }}.key"
    mode: 0600
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Generate CSRs
  shell: "openssl req -new -sha256 -key '{{ letsencrypt_keys_dir }}/{{ item.key }}.key' -subj '/' -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf '[SAN]\nsubjectAltName=DNS:{{ site_hosts | join(',DNS:') }}')) > {{ acme_tiny_data_directory }}/csrs/{{ item.key }}.csr.tmp"
  args:
    executable: /bin/bash
  changed_when: false
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Sync CSRs into place
  command: rsync -ac --info=NAME {{ acme_tiny_data_directory }}/csrs/{{ item.key }}.csr.tmp {{ acme_tiny_data_directory }}/csrs/{{ item.key }}.csr
  register: csr_files
  changed_when: csr_files.stdout == "{{ item.key }}.csr.tmp"
  when: site_uses_letsencrypt
  with_dict: "{{ wordpress_sites }}"

- name: Generate the initial certificate
  command: ./renew-certs.py
  args:
    chdir: "{{ acme_tiny_data_directory }}"
  register: generate_initial_cert
  changed_when: generate_initial_cert.stdout is defined and 'Created' in generate_initial_cert.stdout
  notify: reload nginx
